# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrew/Desktop/InfineumAutomatedBlender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrew/Desktop/InfineumAutomatedBlender

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/Desktop/InfineumAutomatedBlender/CMakeFiles /home/andrew/Desktop/InfineumAutomatedBlender/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/Desktop/InfineumAutomatedBlender/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testStudent

# Build rule for target.
testStudent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testStudent
.PHONY : testStudent

# fast build rule for target.
testStudent/fast:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/build
.PHONY : testStudent/fast

#=============================================================================
# Target rules for targets named testStudent_automoc

# Build rule for target.
testStudent_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testStudent_automoc
.PHONY : testStudent_automoc

# fast build rule for target.
testStudent_automoc/fast:
	$(MAKE) -f CMakeFiles/testStudent_automoc.dir/build.make CMakeFiles/testStudent_automoc.dir/build
.PHONY : testStudent_automoc/fast

Actuator/Actuator.o: Actuator/Actuator.cpp.o

.PHONY : Actuator/Actuator.o

# target to build an object file
Actuator/Actuator.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Actuator.cpp.o
.PHONY : Actuator/Actuator.cpp.o

Actuator/Actuator.i: Actuator/Actuator.cpp.i

.PHONY : Actuator/Actuator.i

# target to preprocess a source file
Actuator/Actuator.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Actuator.cpp.i
.PHONY : Actuator/Actuator.cpp.i

Actuator/Actuator.s: Actuator/Actuator.cpp.s

.PHONY : Actuator/Actuator.s

# target to generate assembly for a file
Actuator/Actuator.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Actuator.cpp.s
.PHONY : Actuator/Actuator.cpp.s

Actuator/DC_Motor/DC_Motor.o: Actuator/DC_Motor/DC_Motor.cpp.o

.PHONY : Actuator/DC_Motor/DC_Motor.o

# target to build an object file
Actuator/DC_Motor/DC_Motor.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/DC_Motor.cpp.o
.PHONY : Actuator/DC_Motor/DC_Motor.cpp.o

Actuator/DC_Motor/DC_Motor.i: Actuator/DC_Motor/DC_Motor.cpp.i

.PHONY : Actuator/DC_Motor/DC_Motor.i

# target to preprocess a source file
Actuator/DC_Motor/DC_Motor.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/DC_Motor.cpp.i
.PHONY : Actuator/DC_Motor/DC_Motor.cpp.i

Actuator/DC_Motor/DC_Motor.s: Actuator/DC_Motor/DC_Motor.cpp.s

.PHONY : Actuator/DC_Motor/DC_Motor.s

# target to generate assembly for a file
Actuator/DC_Motor/DC_Motor.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/DC_Motor.cpp.s
.PHONY : Actuator/DC_Motor/DC_Motor.cpp.s

Actuator/DC_Motor/RotEncoder/RotEncoder.o: Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.o

.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.o

# target to build an object file
Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.o
.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.o

Actuator/DC_Motor/RotEncoder/RotEncoder.i: Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.i

.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.i

# target to preprocess a source file
Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.i
.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.i

Actuator/DC_Motor/RotEncoder/RotEncoder.s: Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.s

.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.s

# target to generate assembly for a file
Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.s
.PHONY : Actuator/DC_Motor/RotEncoder/RotEncoder.cpp.s

Actuator/Stepper/Proximity/Proximity.o: Actuator/Stepper/Proximity/Proximity.cpp.o

.PHONY : Actuator/Stepper/Proximity/Proximity.o

# target to build an object file
Actuator/Stepper/Proximity/Proximity.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Proximity/Proximity.cpp.o
.PHONY : Actuator/Stepper/Proximity/Proximity.cpp.o

Actuator/Stepper/Proximity/Proximity.i: Actuator/Stepper/Proximity/Proximity.cpp.i

.PHONY : Actuator/Stepper/Proximity/Proximity.i

# target to preprocess a source file
Actuator/Stepper/Proximity/Proximity.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Proximity/Proximity.cpp.i
.PHONY : Actuator/Stepper/Proximity/Proximity.cpp.i

Actuator/Stepper/Proximity/Proximity.s: Actuator/Stepper/Proximity/Proximity.cpp.s

.PHONY : Actuator/Stepper/Proximity/Proximity.s

# target to generate assembly for a file
Actuator/Stepper/Proximity/Proximity.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Proximity/Proximity.cpp.s
.PHONY : Actuator/Stepper/Proximity/Proximity.cpp.s

Actuator/Stepper/Stepper.o: Actuator/Stepper/Stepper.cpp.o

.PHONY : Actuator/Stepper/Stepper.o

# target to build an object file
Actuator/Stepper/Stepper.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Stepper.cpp.o
.PHONY : Actuator/Stepper/Stepper.cpp.o

Actuator/Stepper/Stepper.i: Actuator/Stepper/Stepper.cpp.i

.PHONY : Actuator/Stepper/Stepper.i

# target to preprocess a source file
Actuator/Stepper/Stepper.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Stepper.cpp.i
.PHONY : Actuator/Stepper/Stepper.cpp.i

Actuator/Stepper/Stepper.s: Actuator/Stepper/Stepper.cpp.s

.PHONY : Actuator/Stepper/Stepper.s

# target to generate assembly for a file
Actuator/Stepper/Stepper.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Actuator/Stepper/Stepper.cpp.s
.PHONY : Actuator/Stepper/Stepper.cpp.s

CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.o: CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.o

.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.o

# target to build an object file
CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.o
.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.o

CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.i: CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.i

.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.i

# target to preprocess a source file
CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.i
.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.i

CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.s: CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.s

.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.s
.PHONY : CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c.s

CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

CMakeFiles/feature_tests.o: CMakeFiles/feature_tests.c.o

.PHONY : CMakeFiles/feature_tests.o

# target to build an object file
CMakeFiles/feature_tests.c.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/feature_tests.c.o
.PHONY : CMakeFiles/feature_tests.c.o

CMakeFiles/feature_tests.i: CMakeFiles/feature_tests.c.i

.PHONY : CMakeFiles/feature_tests.i

# target to preprocess a source file
CMakeFiles/feature_tests.c.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/feature_tests.c.i
.PHONY : CMakeFiles/feature_tests.c.i

CMakeFiles/feature_tests.s: CMakeFiles/feature_tests.c.s

.PHONY : CMakeFiles/feature_tests.s

# target to generate assembly for a file
CMakeFiles/feature_tests.c.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/CMakeFiles/feature_tests.c.s
.PHONY : CMakeFiles/feature_tests.c.s

FluidTranCntrl/FluidTranCntrl.o: FluidTranCntrl/FluidTranCntrl.cpp.o

.PHONY : FluidTranCntrl/FluidTranCntrl.o

# target to build an object file
FluidTranCntrl/FluidTranCntrl.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/FluidTranCntrl/FluidTranCntrl.cpp.o
.PHONY : FluidTranCntrl/FluidTranCntrl.cpp.o

FluidTranCntrl/FluidTranCntrl.i: FluidTranCntrl/FluidTranCntrl.cpp.i

.PHONY : FluidTranCntrl/FluidTranCntrl.i

# target to preprocess a source file
FluidTranCntrl/FluidTranCntrl.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/FluidTranCntrl/FluidTranCntrl.cpp.i
.PHONY : FluidTranCntrl/FluidTranCntrl.cpp.i

FluidTranCntrl/FluidTranCntrl.s: FluidTranCntrl/FluidTranCntrl.cpp.s

.PHONY : FluidTranCntrl/FluidTranCntrl.s

# target to generate assembly for a file
FluidTranCntrl/FluidTranCntrl.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/FluidTranCntrl/FluidTranCntrl.cpp.s
.PHONY : FluidTranCntrl/FluidTranCntrl.cpp.s

HeatCntrl/HeatCntrl.o: HeatCntrl/HeatCntrl.cpp.o

.PHONY : HeatCntrl/HeatCntrl.o

# target to build an object file
HeatCntrl/HeatCntrl.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/HeatCntrl.cpp.o
.PHONY : HeatCntrl/HeatCntrl.cpp.o

HeatCntrl/HeatCntrl.i: HeatCntrl/HeatCntrl.cpp.i

.PHONY : HeatCntrl/HeatCntrl.i

# target to preprocess a source file
HeatCntrl/HeatCntrl.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/HeatCntrl.cpp.i
.PHONY : HeatCntrl/HeatCntrl.cpp.i

HeatCntrl/HeatCntrl.s: HeatCntrl/HeatCntrl.cpp.s

.PHONY : HeatCntrl/HeatCntrl.s

# target to generate assembly for a file
HeatCntrl/HeatCntrl.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/HeatCntrl.cpp.s
.PHONY : HeatCntrl/HeatCntrl.cpp.s

HeatCntrl/tempMeasurement/tempMeasurement.o: HeatCntrl/tempMeasurement/tempMeasurement.cpp.o

.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.o

# target to build an object file
HeatCntrl/tempMeasurement/tempMeasurement.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/tempMeasurement/tempMeasurement.cpp.o
.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.cpp.o

HeatCntrl/tempMeasurement/tempMeasurement.i: HeatCntrl/tempMeasurement/tempMeasurement.cpp.i

.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.i

# target to preprocess a source file
HeatCntrl/tempMeasurement/tempMeasurement.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/tempMeasurement/tempMeasurement.cpp.i
.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.cpp.i

HeatCntrl/tempMeasurement/tempMeasurement.s: HeatCntrl/tempMeasurement/tempMeasurement.cpp.s

.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.s

# target to generate assembly for a file
HeatCntrl/tempMeasurement/tempMeasurement.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/HeatCntrl/tempMeasurement/tempMeasurement.cpp.s
.PHONY : HeatCntrl/tempMeasurement/tempMeasurement.cpp.s

PumpCntrl/PumpCntrl.o: PumpCntrl/PumpCntrl.cpp.o

.PHONY : PumpCntrl/PumpCntrl.o

# target to build an object file
PumpCntrl/PumpCntrl.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/PumpCntrl/PumpCntrl.cpp.o
.PHONY : PumpCntrl/PumpCntrl.cpp.o

PumpCntrl/PumpCntrl.i: PumpCntrl/PumpCntrl.cpp.i

.PHONY : PumpCntrl/PumpCntrl.i

# target to preprocess a source file
PumpCntrl/PumpCntrl.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/PumpCntrl/PumpCntrl.cpp.i
.PHONY : PumpCntrl/PumpCntrl.cpp.i

PumpCntrl/PumpCntrl.s: PumpCntrl/PumpCntrl.cpp.s

.PHONY : PumpCntrl/PumpCntrl.s

# target to generate assembly for a file
PumpCntrl/PumpCntrl.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/PumpCntrl/PumpCntrl.cpp.s
.PHONY : PumpCntrl/PumpCntrl.cpp.s

SystemInterface/AlarmSys/AlarmSys.o: SystemInterface/AlarmSys/AlarmSys.cpp.o

.PHONY : SystemInterface/AlarmSys/AlarmSys.o

# target to build an object file
SystemInterface/AlarmSys/AlarmSys.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/AlarmSys/AlarmSys.cpp.o
.PHONY : SystemInterface/AlarmSys/AlarmSys.cpp.o

SystemInterface/AlarmSys/AlarmSys.i: SystemInterface/AlarmSys/AlarmSys.cpp.i

.PHONY : SystemInterface/AlarmSys/AlarmSys.i

# target to preprocess a source file
SystemInterface/AlarmSys/AlarmSys.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/AlarmSys/AlarmSys.cpp.i
.PHONY : SystemInterface/AlarmSys/AlarmSys.cpp.i

SystemInterface/AlarmSys/AlarmSys.s: SystemInterface/AlarmSys/AlarmSys.cpp.s

.PHONY : SystemInterface/AlarmSys/AlarmSys.s

# target to generate assembly for a file
SystemInterface/AlarmSys/AlarmSys.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/AlarmSys/AlarmSys.cpp.s
.PHONY : SystemInterface/AlarmSys/AlarmSys.cpp.s

SystemInterface/Logger/Logger.o: SystemInterface/Logger/Logger.cpp.o

.PHONY : SystemInterface/Logger/Logger.o

# target to build an object file
SystemInterface/Logger/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/Logger/Logger.cpp.o
.PHONY : SystemInterface/Logger/Logger.cpp.o

SystemInterface/Logger/Logger.i: SystemInterface/Logger/Logger.cpp.i

.PHONY : SystemInterface/Logger/Logger.i

# target to preprocess a source file
SystemInterface/Logger/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/Logger/Logger.cpp.i
.PHONY : SystemInterface/Logger/Logger.cpp.i

SystemInterface/Logger/Logger.s: SystemInterface/Logger/Logger.cpp.s

.PHONY : SystemInterface/Logger/Logger.s

# target to generate assembly for a file
SystemInterface/Logger/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/Logger/Logger.cpp.s
.PHONY : SystemInterface/Logger/Logger.cpp.s

SystemInterface/SystemInterface.o: SystemInterface/SystemInterface.cpp.o

.PHONY : SystemInterface/SystemInterface.o

# target to build an object file
SystemInterface/SystemInterface.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/SystemInterface.cpp.o
.PHONY : SystemInterface/SystemInterface.cpp.o

SystemInterface/SystemInterface.i: SystemInterface/SystemInterface.cpp.i

.PHONY : SystemInterface/SystemInterface.i

# target to preprocess a source file
SystemInterface/SystemInterface.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/SystemInterface.cpp.i
.PHONY : SystemInterface/SystemInterface.cpp.i

SystemInterface/SystemInterface.s: SystemInterface/SystemInterface.cpp.s

.PHONY : SystemInterface/SystemInterface.s

# target to generate assembly for a file
SystemInterface/SystemInterface.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/SystemInterface/SystemInterface.cpp.s
.PHONY : SystemInterface/SystemInterface.cpp.s

Tools/TimerAPI.o: Tools/TimerAPI.c.o

.PHONY : Tools/TimerAPI.o

# target to build an object file
Tools/TimerAPI.c.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/TimerAPI.c.o
.PHONY : Tools/TimerAPI.c.o

Tools/TimerAPI.i: Tools/TimerAPI.c.i

.PHONY : Tools/TimerAPI.i

# target to preprocess a source file
Tools/TimerAPI.c.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/TimerAPI.c.i
.PHONY : Tools/TimerAPI.c.i

Tools/TimerAPI.s: Tools/TimerAPI.c.s

.PHONY : Tools/TimerAPI.s

# target to generate assembly for a file
Tools/TimerAPI.c.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/TimerAPI.c.s
.PHONY : Tools/TimerAPI.c.s

Tools/gpioTool.o: Tools/gpioTool.cpp.o

.PHONY : Tools/gpioTool.o

# target to build an object file
Tools/gpioTool.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/gpioTool.cpp.o
.PHONY : Tools/gpioTool.cpp.o

Tools/gpioTool.i: Tools/gpioTool.cpp.i

.PHONY : Tools/gpioTool.i

# target to preprocess a source file
Tools/gpioTool.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/gpioTool.cpp.i
.PHONY : Tools/gpioTool.cpp.i

Tools/gpioTool.s: Tools/gpioTool.cpp.s

.PHONY : Tools/gpioTool.s

# target to generate assembly for a file
Tools/gpioTool.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/gpioTool.cpp.s
.PHONY : Tools/gpioTool.cpp.s

Tools/i2cTool.o: Tools/i2cTool.cpp.o

.PHONY : Tools/i2cTool.o

# target to build an object file
Tools/i2cTool.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/i2cTool.cpp.o
.PHONY : Tools/i2cTool.cpp.o

Tools/i2cTool.i: Tools/i2cTool.cpp.i

.PHONY : Tools/i2cTool.i

# target to preprocess a source file
Tools/i2cTool.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/i2cTool.cpp.i
.PHONY : Tools/i2cTool.cpp.i

Tools/i2cTool.s: Tools/i2cTool.cpp.s

.PHONY : Tools/i2cTool.s

# target to generate assembly for a file
Tools/i2cTool.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/Tools/i2cTool.cpp.s
.PHONY : Tools/i2cTool.cpp.s

ValveCntrl/ValveCntrl.o: ValveCntrl/ValveCntrl.cpp.o

.PHONY : ValveCntrl/ValveCntrl.o

# target to build an object file
ValveCntrl/ValveCntrl.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/ValveCntrl/ValveCntrl.cpp.o
.PHONY : ValveCntrl/ValveCntrl.cpp.o

ValveCntrl/ValveCntrl.i: ValveCntrl/ValveCntrl.cpp.i

.PHONY : ValveCntrl/ValveCntrl.i

# target to preprocess a source file
ValveCntrl/ValveCntrl.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/ValveCntrl/ValveCntrl.cpp.i
.PHONY : ValveCntrl/ValveCntrl.cpp.i

ValveCntrl/ValveCntrl.s: ValveCntrl/ValveCntrl.cpp.s

.PHONY : ValveCntrl/ValveCntrl.s

# target to generate assembly for a file
ValveCntrl/ValveCntrl.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/ValveCntrl/ValveCntrl.cpp.s
.PHONY : ValveCntrl/ValveCntrl.cpp.s

mixCntrl/mixCntrl.o: mixCntrl/mixCntrl.cpp.o

.PHONY : mixCntrl/mixCntrl.o

# target to build an object file
mixCntrl/mixCntrl.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/mixCntrl/mixCntrl.cpp.o
.PHONY : mixCntrl/mixCntrl.cpp.o

mixCntrl/mixCntrl.i: mixCntrl/mixCntrl.cpp.i

.PHONY : mixCntrl/mixCntrl.i

# target to preprocess a source file
mixCntrl/mixCntrl.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/mixCntrl/mixCntrl.cpp.i
.PHONY : mixCntrl/mixCntrl.cpp.i

mixCntrl/mixCntrl.s: mixCntrl/mixCntrl.cpp.s

.PHONY : mixCntrl/mixCntrl.s

# target to generate assembly for a file
mixCntrl/mixCntrl.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/mixCntrl/mixCntrl.cpp.s
.PHONY : mixCntrl/mixCntrl.cpp.s

testStudent_automoc.o: testStudent_automoc.cpp.o

.PHONY : testStudent_automoc.o

# target to build an object file
testStudent_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/testStudent_automoc.cpp.o
.PHONY : testStudent_automoc.cpp.o

testStudent_automoc.i: testStudent_automoc.cpp.i

.PHONY : testStudent_automoc.i

# target to preprocess a source file
testStudent_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/testStudent_automoc.cpp.i
.PHONY : testStudent_automoc.cpp.i

testStudent_automoc.s: testStudent_automoc.cpp.s

.PHONY : testStudent_automoc.s

# target to generate assembly for a file
testStudent_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/testStudent_automoc.cpp.s
.PHONY : testStudent_automoc.cpp.s

topLevel/main.o: topLevel/main.cpp.o

.PHONY : topLevel/main.o

# target to build an object file
topLevel/main.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/main.cpp.o
.PHONY : topLevel/main.cpp.o

topLevel/main.i: topLevel/main.cpp.i

.PHONY : topLevel/main.i

# target to preprocess a source file
topLevel/main.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/main.cpp.i
.PHONY : topLevel/main.cpp.i

topLevel/main.s: topLevel/main.cpp.s

.PHONY : topLevel/main.s

# target to generate assembly for a file
topLevel/main.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/main.cpp.s
.PHONY : topLevel/main.cpp.s

topLevel/systeminterfaceqt.o: topLevel/systeminterfaceqt.cpp.o

.PHONY : topLevel/systeminterfaceqt.o

# target to build an object file
topLevel/systeminterfaceqt.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/systeminterfaceqt.cpp.o
.PHONY : topLevel/systeminterfaceqt.cpp.o

topLevel/systeminterfaceqt.i: topLevel/systeminterfaceqt.cpp.i

.PHONY : topLevel/systeminterfaceqt.i

# target to preprocess a source file
topLevel/systeminterfaceqt.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/systeminterfaceqt.cpp.i
.PHONY : topLevel/systeminterfaceqt.cpp.i

topLevel/systeminterfaceqt.s: topLevel/systeminterfaceqt.cpp.s

.PHONY : topLevel/systeminterfaceqt.s

# target to generate assembly for a file
topLevel/systeminterfaceqt.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/systeminterfaceqt.cpp.s
.PHONY : topLevel/systeminterfaceqt.cpp.s

topLevel/testStudent_automoc.o: topLevel/testStudent_automoc.cpp.o

.PHONY : topLevel/testStudent_automoc.o

# target to build an object file
topLevel/testStudent_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/testStudent_automoc.cpp.o
.PHONY : topLevel/testStudent_automoc.cpp.o

topLevel/testStudent_automoc.i: topLevel/testStudent_automoc.cpp.i

.PHONY : topLevel/testStudent_automoc.i

# target to preprocess a source file
topLevel/testStudent_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/testStudent_automoc.cpp.i
.PHONY : topLevel/testStudent_automoc.cpp.i

topLevel/testStudent_automoc.s: topLevel/testStudent_automoc.cpp.s

.PHONY : topLevel/testStudent_automoc.s

# target to generate assembly for a file
topLevel/testStudent_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/topLevel/testStudent_automoc.cpp.s
.PHONY : topLevel/testStudent_automoc.cpp.s

weightMeasurement/weightMeasurement.o: weightMeasurement/weightMeasurement.cpp.o

.PHONY : weightMeasurement/weightMeasurement.o

# target to build an object file
weightMeasurement/weightMeasurement.cpp.o:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/weightMeasurement/weightMeasurement.cpp.o
.PHONY : weightMeasurement/weightMeasurement.cpp.o

weightMeasurement/weightMeasurement.i: weightMeasurement/weightMeasurement.cpp.i

.PHONY : weightMeasurement/weightMeasurement.i

# target to preprocess a source file
weightMeasurement/weightMeasurement.cpp.i:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/weightMeasurement/weightMeasurement.cpp.i
.PHONY : weightMeasurement/weightMeasurement.cpp.i

weightMeasurement/weightMeasurement.s: weightMeasurement/weightMeasurement.cpp.s

.PHONY : weightMeasurement/weightMeasurement.s

# target to generate assembly for a file
weightMeasurement/weightMeasurement.cpp.s:
	$(MAKE) -f CMakeFiles/testStudent.dir/build.make CMakeFiles/testStudent.dir/weightMeasurement/weightMeasurement.cpp.s
.PHONY : weightMeasurement/weightMeasurement.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... testStudent"
	@echo "... testStudent_automoc"
	@echo "... Actuator/Actuator.o"
	@echo "... Actuator/Actuator.i"
	@echo "... Actuator/Actuator.s"
	@echo "... Actuator/DC_Motor/DC_Motor.o"
	@echo "... Actuator/DC_Motor/DC_Motor.i"
	@echo "... Actuator/DC_Motor/DC_Motor.s"
	@echo "... Actuator/DC_Motor/RotEncoder/RotEncoder.o"
	@echo "... Actuator/DC_Motor/RotEncoder/RotEncoder.i"
	@echo "... Actuator/DC_Motor/RotEncoder/RotEncoder.s"
	@echo "... Actuator/Stepper/Proximity/Proximity.o"
	@echo "... Actuator/Stepper/Proximity/Proximity.i"
	@echo "... Actuator/Stepper/Proximity/Proximity.s"
	@echo "... Actuator/Stepper/Stepper.o"
	@echo "... Actuator/Stepper/Stepper.i"
	@echo "... Actuator/Stepper/Stepper.s"
	@echo "... CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.o"
	@echo "... CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.i"
	@echo "... CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.s"
	@echo "... CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... CMakeFiles/feature_tests.o"
	@echo "... CMakeFiles/feature_tests.i"
	@echo "... CMakeFiles/feature_tests.s"
	@echo "... FluidTranCntrl/FluidTranCntrl.o"
	@echo "... FluidTranCntrl/FluidTranCntrl.i"
	@echo "... FluidTranCntrl/FluidTranCntrl.s"
	@echo "... HeatCntrl/HeatCntrl.o"
	@echo "... HeatCntrl/HeatCntrl.i"
	@echo "... HeatCntrl/HeatCntrl.s"
	@echo "... HeatCntrl/tempMeasurement/tempMeasurement.o"
	@echo "... HeatCntrl/tempMeasurement/tempMeasurement.i"
	@echo "... HeatCntrl/tempMeasurement/tempMeasurement.s"
	@echo "... PumpCntrl/PumpCntrl.o"
	@echo "... PumpCntrl/PumpCntrl.i"
	@echo "... PumpCntrl/PumpCntrl.s"
	@echo "... SystemInterface/AlarmSys/AlarmSys.o"
	@echo "... SystemInterface/AlarmSys/AlarmSys.i"
	@echo "... SystemInterface/AlarmSys/AlarmSys.s"
	@echo "... SystemInterface/Logger/Logger.o"
	@echo "... SystemInterface/Logger/Logger.i"
	@echo "... SystemInterface/Logger/Logger.s"
	@echo "... SystemInterface/SystemInterface.o"
	@echo "... SystemInterface/SystemInterface.i"
	@echo "... SystemInterface/SystemInterface.s"
	@echo "... Tools/TimerAPI.o"
	@echo "... Tools/TimerAPI.i"
	@echo "... Tools/TimerAPI.s"
	@echo "... Tools/gpioTool.o"
	@echo "... Tools/gpioTool.i"
	@echo "... Tools/gpioTool.s"
	@echo "... Tools/i2cTool.o"
	@echo "... Tools/i2cTool.i"
	@echo "... Tools/i2cTool.s"
	@echo "... ValveCntrl/ValveCntrl.o"
	@echo "... ValveCntrl/ValveCntrl.i"
	@echo "... ValveCntrl/ValveCntrl.s"
	@echo "... mixCntrl/mixCntrl.o"
	@echo "... mixCntrl/mixCntrl.i"
	@echo "... mixCntrl/mixCntrl.s"
	@echo "... testStudent_automoc.o"
	@echo "... testStudent_automoc.i"
	@echo "... testStudent_automoc.s"
	@echo "... topLevel/main.o"
	@echo "... topLevel/main.i"
	@echo "... topLevel/main.s"
	@echo "... topLevel/systeminterfaceqt.o"
	@echo "... topLevel/systeminterfaceqt.i"
	@echo "... topLevel/systeminterfaceqt.s"
	@echo "... topLevel/testStudent_automoc.o"
	@echo "... topLevel/testStudent_automoc.i"
	@echo "... topLevel/testStudent_automoc.s"
	@echo "... weightMeasurement/weightMeasurement.o"
	@echo "... weightMeasurement/weightMeasurement.i"
	@echo "... weightMeasurement/weightMeasurement.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

